argotorg/solidity-website

src/utils/getAllEvents.ts

Adds a sort function to the events when being fetched using `utils/getAllEvents.ts`.
Results in the most recent past events being listed first in the homepage preview.

Sort events by endDate on fetch

---

src/pages/index.tsx

**Description**
This PR addresses an overflow issue caused by setting the max-width to 8ch on the container, which does not account for variable font widths. When a font-face with a larger width is used, this can lead to unwanted overflow.
**Changes:**
- Removed max-width from container.
- Applied max-width directly to text element.
**Screenshot**

Apply max-width to text element instead of container

---

src/events/solidity-summit-2023.md

We'll direct to https://devconnect.org/schedule until we have updated summit.soliditylang.org

Change link for Solidity Summit 2023 to Devconnect page

---

src/pages/blog/[YYYY]/[MM]/[DD]/[post].tsx

Centers content and hero for blog posts.

Blog post: cap width and center [Fixes #15]

---

src/posts/2023-07-19-missing-side-effects-on-selector-access-bug.md

Blog post for https://github.com/ethereum/solidity/pull/14366
It was originally created in the old solidity-blog repo: https://github.com/ethereum/solidity-blog/pull/218

Add blog post about missing side effects on selector access bug

---

src/components/Link.tsx
src/constants.ts
src/pages/index.tsx

Our homepage currently uses the 'blog.soliditylang.org' link. This is recognized as an external link, which triggers a complete page refresh and opens in a new tab.
In this PR, I've updated the link to use 'soliditylang.org/blog/', the recognized internal link. This should avoid the page reloading and provide a smoother user experience.

Use internal link for blog callout

---

src/components/Footer.tsx

Removes the inline-padding used on footer links on mobile. Not needed when links stack vertically.
- Fixes #16

Remove indentation on mobile footer links [Fixes #16]

---

src/constants.ts

Removes Gitter social link, which is redirecting to the Matrix server already being linked to.
- Fixes #18

Remove deprecated/redundant Gitter link [Fixes #18]

---

src/pages/index.tsx

This PR updates the link in the "Solidity is evolving rapidly" section of the homepage to point to a current GitHub project board. The current copy reads like this:
> **Solidity is evolving rapidly**
> We aim for a regular (non-breaking) release every month, with approximately one breaking release per year. You can follow the implementation status of new features in the [Solidity GitHub project](https://github.com/ethereum/solidity/projects/17).
Currently, the link [goes to an old project from 2018 called "Coinspect Audit"](https://github.com/ethereum/solidity/projects/17).
This PR updates the link so it goes to ["Solidity Roadmap"](https://github.com/orgs/ethereum/projects/26).

Update GitHub project link

---

src/events/solidity-summit-2023.md

I updated https://summit.soliditylang.org/ to a 2023 "coming soon" stage so I believe we can add the link back into the main page. :)

Update Solidity Summit 2023 Card to point to summit.soliditylang.org

---

src/components/Link.tsx

Adds unicode modifier to force the external link arrow to always display in the non-emoji force.
The modifier code `FE0E` (`\uFE0E` in JavaScript) can be placed after a unicode character to avoid ambiguity and force the non-emoji rendering:
---
The opposite can be done with `\uFE0F` which will force the emoji form:
- Fixes #6

Force non-emoji unicode arrow [Fixes #6]

---

src/pages/use-cases.tsx

Noticed no spacing between the link and words. Fixed in this PR.

Fix typo on use cases page

---

package.json
yarn.lock

See recommended secure update: https://github.com/ethereum/solidity-website/security/dependabot/5

Bump nextjs from 13.1.6 to 13.5.6 and postcss from 8.4.14 to 8.4.31

---

src/styles/MDStyles.tsx

- Adds `fontSize` props to markdown heading items to explicitly declare sizes
- [Fixes #67]

Fix heading font sizes for blog

---

src/hooks/useCleanRouterPath.ts

- Updates the logic for `useCleanRouterPath` function; ensures removal of all query params, hash links, and trailing slashes
- This fixes a bug where the path of the current page had a trailing slash and was not being recognized in the ordered list of blog post pages, thus didn't know where it properly fit in the ordering.
Notice on the first post we still have a "Previous" button which links to `/blogundefined`, and the "Next" button takes user to the same page:
With fix:

Patch next/previous blog post navigation bug

---

src/pages/index.tsx

---
Updated to display and link to [Solidity 0.8.26](https://soliditylang.org/blog/2024/05/21/solidity-0.8.26-release-announcement).

Update index.tsx to display latest release: v0.8.26

---

src/components/Footer.tsx

I noticed the website footer had 2023 as the copyright year, so here is a simple PR to update it to 2024.

Update Copyright Year in Footer

---

package.json
yarn.lock

Reverts ethereum/solidity-website#114
(Since CI builds failed on it, since apparently we also need a node bump, I'm reverting for now)

Revert "Bump next from 13.5.6 to 14.2.10"

---

src/posts/2021-02-01-launching-the-solidity-forum.md
src/posts/2021-02-15-contributing-to-solidity-101.md

I identified and updated broken links in two Markdown files within the repository:
1. **`2021-02-01-launching-the-solidity-forum.md`**  
- Updated the link to the correct Solidity GitHub project page:  
- From: `https://github.com/ethereum/solidity/projects/43`  
- To: `https://github.com/orgs/ethereum/projects/17`
2. **`2021-02-15-contributing-to-solidity-101.md`**  
- Updated the link to the same corrected GitHub project page.

fix: 404's links

---

.github/workflows/nextjs.yml

Same as #127 but bumping deploy-pages action to v4: https://github.com/ethereum/solidity-website/actions/runs/13814223102

Bump deploy-pages to v4

---

src/posts/2025-03-12-solidity-0.8.29-release-announcement.md

- The concerns about missing checks on `.send()`/`.transfer()`.
- I also realized that we did not mention StackTooDeep and that's something of high interest to users.

Address 0.8.29 release concerns
